services:
  app:
    build:
      args:
        user: ${USER}
        uid: 1000
      context: ./
      dockerfile: ./.devops/php/Dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - single-responsibility-principle
  db:
    image: mysql:8.0
    platform: linux/x86_64
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: solid
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: toorcdp
    volumes:
      - ./.devops/mysql/script.sql:/docker-entrypoint-initdb.d/script.sql
      - ./.devops/mysql/dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - single-responsibility-principle
networks:
  single-responsibility-principle:
    driver: bridge
